behaviors:
  BoomBehaviour:
    trainer_type: ppo
    hyperparameters:
      batch_size: 100
      buffer_size: 2048
      learning_rate: 1e-4
      beta: 1.0e-5
      beta_schedule: constant
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true
      hidden_units: 64
      num_layers: 2
      # memory
      memory:
        sequence_length: 6
        memory_size: 256
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1.0
    max_steps: 999999999
    time_horizon: 100
    summary_freq: 500
    